---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-newsaggregator-teamdev-com-v1-feed
  failurePolicy: Fail
  name: vfeed.kb.io
  rules:
  - apiGroups:
    - newsaggregator.teamdev.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - feeds
  sideEffects: None
