version: '3'

tasks:
  pre-launch:
    label: "Prepare code for launching"
    summary: |
      This task formats code, optimizes dependencies and runs staticcheck tool
    cmds:
      - gofmt
      - go mod tidy
      - staticcheck

  launch:
    label: "Build and launch the code"
    summary: |
      This task builds executable file and runs it.
    cmds:
      - go build -o ./bin/server.exe
      - ./bin/server.exe

  test:
    label: "Run all tests in application"
    summary: |
      This task runs go test ./cmd/... which tests all available files from all child folders
    cmd: go test ./cmd/...

  testingDone:
    summary: |
      Run Go tests with coverage report and fail if coverage is below 80%
    cmds:
      - go test -coverprofile=coverage.out
      - |
        coverage=$(go tool cover -func=coverage.out | grep -E '^total:' | awk '{print $3}' | sed 's/%//')
        threshold=80.0
        if (( $(echo "$coverage < $threshold" | bc -l) )); then
          echo "Coverage $coverage% is below the threshold of $threshold%"
          exit 1
        else
          echo "Coverage $coverage% meets the threshold of $threshold%"
        fi

  dockerBuild:
    label: "Build the docker image using Dockerfile with go-gator as a name"
    cmd: docker build -t go-gator .

  publish:
    label: "Push the image to dockerhub"
    cmds:
      - docker login
      - docker push werniq/go-gator
