version: '3'

env:
  # this variables can be specified when running task like this
  # task publish DOCKER_IMAGE_NAME=new-image-title DOCKER_IMAGE_TAG=1.0.1
  DOCKER_IMAGE_NAME: '{{ .DOCKER_IMAGE_NAME | default "go-gator" }}'
  DOCKER_USERNAME:   '{{ .DOCKER_USERNAME | default "qniw984" }}'
  DOCKER_IMAGE_TAG:  '{{ .DOCKER_IMAGE_TAG | default "latest" }}'
  DOCKERHUB_USERNAME: '{{ .DOCKER_LOGIN_USERNAME }}'
  DOCKERHUB_PASSWORD: '{{ .DOCKERHUB_PASSWORD }}'
  TESTDIR_NAME:      '{{ .TESTDIR_NAME | default "pkg_tests" }}'

tasks:
  fmt:
    desc: Format all code in all subdirectories
    cmds:
      - go fmt ./...

  vet:
    desc: Format all code in all subdirectories
    cmds:
      - go vet ./...

  clean:
    desc: Clean go mod dependencies
    cmds:
      - go mod tidy

  stch:
    desc: Run staticcheck
    cmds:
      - staticcheck ./...

  pre-launch:
    label: Prepare code before launching
    desc: Formats code, optimizes dependencies and runs staticcheck tool
    deps:
      - fmt
      - vet
      - clean
      - stch

  build:
    label: Build go-gator
    desc: Builds executable file for the server
    cmds:
      - go build

  run:
    label: Running go-gator
    desc: Run the application
    cmds:
      - go run .

  test:
    label: Run all tests in application
    desc: This task runs all available test files from all child folders
    # Compiling and running tests separately to handle relative paths correctly
    cmd: |
      go test ./... -v

  docker-build:
    desc: Build the docker image using Dockerfile with go-gator as a name
    cmd: docker build -t {{ .DOCKER_IMAGE_NAME }} .

  docker-run:
    desc: Run docker image
    cmd: docker run {{ .DOCKER_IMAGE_NAME }}

  publish:
    label: Pushing image to dockerhub
    desc: Push docker image to dockerhub
    deps:
     - docker-build
    cmds:
      - docker login -u {{ .DOCKERHUB_USERNAME }} -p {{ .DOCKERHUB_PASSWORD }}
      - docker push {{ .DOCKER_USERNAME }}/{{ .DOCKER_IMAGE_NAME }}:{{ .DOCKER_IMAGE_TAG }}

  deploy:
    desc: Deploy news aggregator app on the Kubernetes cluster
    cmds:
      - kubectl apply -f templates/

  undeploy:
    desc: Remove go-gator from kubernetes Cluster
    cmds:
      - kubectl delete -f templates/

  installVpa:
    desc: Install Vertical Pod Autoscaler
    cmds:
      - git clone https://github.com/kubernetes/autoscaler.git
      - cd autoscaler/vertical-pod-autoscaler
      - git checkout origin/vpa-release-1.0
      - REGISTRY=registry.k8s.io/autoscaling TAG=1.0.0 ./hack/vpa-process-yamls.sh apply
