apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  isCA: false
  commonName: go-gator-server
  secretName: cert-secret
  privateKey:
    algorithm: {{ .Values.certificate.privateKey.algorithm }}
    size: {{ .Values.certificate.privateKey.size }}
  usages:
    - server auth
    - client auth
  issuerRef:
    name: {{ .Values.issuer.name }}