apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go-gator-server
  namespace: go-gator
spec:
  isCA: false
  commonName: go-gator-server
  secretName: cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    - "go-gator-svc.go-gator.svc.cluster.local"
    - "go-gator-server"
  issuerRef:
    name: go-gator-self-signed-ca-issuer