apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-gator-pv
  namespace: go-gator
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-gator-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi