apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-gator-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi