apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.goGatorService.name }}
  namespace: {{ .Values.goGatorService.namespace }}
rules:
  - apiGroups: ["v1"]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.cronJobRole.name }}
  namespace: {{ .Values.cronJobRole.namespace }}
