apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: go-gator-vpa
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    apiVersion: {{ .Values.vpa.targetRef.apiVersion }}
    kind:       {{ .Values.vpa.targetRef.kind }}
    name:       {{ .Values.vpa.targetRef.name }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Values.vpa.resourcePolicy.containerName }}
        minAllowed:
          cpu: {{ .Values.vpa.resourcePolicy.minAllowed.cpu }}
          memory: {{ .Values.vpa.resourcePolicy.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.vpa.resourcePolicy.maxAllowed.cpu }}
          memory: {{ .Values.vpa.resourcePolicy.maxAllowed.memory }}