apiVersion: v1
kind: Pod

metadata:
  name: Go-gator
  namespace: my-namespace
  labels:
    name: go-gator

spec:
  containers:
    - name: Go-Gator
      image: qniw984/go-gator:latest
      ports:
        - containerPort: 80
          name: https-go-gator