apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.4
    chart: external-secrets
    helm:
      valuesObjects:
        crds:
          enabled: true
        prometheus:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: go-gator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true