version: '3'

env:
  DOCKER_IMAGE_NAME: '{{ .DOCKER_IMAGE_NAME | default "news-fetching-job" }}'
  DOCKER_USERNAME:   '{{ .DOCKER_USERNAME | default "qniw984" }}'
  DOCKER_IMAGE_TAG:  '{{ .DOCKER_IMAGE_TAG | default "latest" }}'
  DOCKERHUB_USERNAME: '{{ .DOCKER_LOGIN_USERNAME }}'
  DOCKERHUB_PASSWORD: '{{ .DOCKERHUB_PASSWORD }}'

tasks:
  build:
    label: Build news-fetching-job
    desc: Builds executable file for the job
    cmds:
      - go build -o ./news-fetching-job

  run:
    label: Running job
    desc: Run news-fetching-job
    cmds:
      - go run .

  test:
    label: Run all tests in application
    desc: This task runs all available test files from all child folders
    cmd: |
      go test ./...

  docker-build:
    desc: Build the docker image using Dockerfile with go-gator as a name
    cmd: docker build -t {{ .DOCKER_IMAGE_NAME }} -f ./Dockerfile ..

  docker-run:
    desc: Run docker image
    cmd: docker run {{ .DOCKER_IMAGE_NAME }}

  publish:
    label: Pushing image to dockerhub
    desc: Push docker image to dockerhub
    deps:
      - docker-build
    cmds:
      - docker login -u {{ .DOCKERHUB_USERNAME }} -p {{ .DOCKERHUB_PASSWORD }}
      - docker push {{ .DOCKER_USERNAME }}/{{ .DOCKER_IMAGE_NAME }}:{{ .DOCKER_IMAGE_TAG }}