---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - newsaggregator.teamdev.com
  resources:
  - feeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newsaggregator.teamdev.com
  resources:
  - feeds/finalizers
  verbs:
  - update
- apiGroups:
  - newsaggregator.teamdev.com
  resources:
  - feeds/status
  verbs:
  - get
  - patch
  - update
