# permissions for end users to edit sources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: source-editor-role
rules:
- apiGroups:
  - newsaggregator.teamdev.com
  resources:
  - sources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newsaggregator.teamdev.com
  resources:
  - sources/status
  verbs:
  - get
