apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-client
  namespace: go-gator
spec:
  secretName: cert-secret
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - "go-gator-svc.go-gator.svc.cluster.local"
    - "go-gator-server"
  issuerRef:
    name: go-gator-ca-issuer