apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-gator-day-0-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/werniq/go-gator
    path: day-0
    targetRevision: feature/argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: go-gator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
