apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-gator-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 406477933661.dkr.ecr.us-east-2.amazonaws.com/qniw984
    targetRevision: 0.1.0
    chart: go-gator-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: go-gator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
