apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sa.name }}
  namespace:  {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
  namespace:  {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace:  {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sa.name }}
    namespace: {{ .Values.namespace }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup: ""
