apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-registry-helper
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 */12 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-health-check
          containers:
            - name: ecr-registry-helper
              image: odaniait/aws-kubectl:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: {{ .Values.dockerSecretName }}
                - configMapRef:
                    name: ecr-registry-helper-cm
              command:
                - /bin/sh
                - -c
                - |-
                  ECR_TOKEN=`aws ecr get-login-password --region ${AWS_REGION}`
                  NAMESPACE_NAME=go-gator
                  kubectl patch secret -n go-gator aws-secret --type=json
                  -p='[{"op": "replace", "path": "/data/", "value": "{"": "", "": ""}"}]'
                  echo "Secret was successfully patched at $(date)"
          restartPolicy: Never
