apiVersion: v2
name: go-gator
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: v1.15.3
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled
  - name: vertical-pod-autoscaler
    repository: https://stevehipwell.github.io/helm-charts/
    version: 1.7.1