apiVersion: v2
name: go-gator
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: 1.15.3
    repository: https://charts.jetstack.io