//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotNews) DeepCopyInto(out *HotNews) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotNews.
func (in *HotNews) DeepCopy() *HotNews {
	if in == nil {
		return nil
	}
	out := new(HotNews)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HotNews) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotNewsList) DeepCopyInto(out *HotNewsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HotNews, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotNewsList.
func (in *HotNewsList) DeepCopy() *HotNewsList {
	if in == nil {
		return nil
	}
	out := new(HotNewsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HotNewsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotNewsSpec) DeepCopyInto(out *HotNewsSpec) {
	*out = *in
	if in.Feeds != nil {
		in, out := &in.Feeds, &out.Feeds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FeedGroups != nil {
		in, out := &in.FeedGroups, &out.FeedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SummaryConfig = in.SummaryConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotNewsSpec.
func (in *HotNewsSpec) DeepCopy() *HotNewsSpec {
	if in == nil {
		return nil
	}
	out := new(HotNewsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotNewsStatus) DeepCopyInto(out *HotNewsStatus) {
	*out = *in
	if in.ArticlesTitles != nil {
		in, out := &in.ArticlesTitles, &out.ArticlesTitles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotNewsStatus.
func (in *HotNewsStatus) DeepCopy() *HotNewsStatus {
	if in == nil {
		return nil
	}
	out := new(HotNewsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SummaryConfig) DeepCopyInto(out *SummaryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SummaryConfig.
func (in *SummaryConfig) DeepCopy() *SummaryConfig {
	if in == nil {
		return nil
	}
	out := new(SummaryConfig)
	in.DeepCopyInto(out)
	return out
}
