apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-gator-fetching-news-job
  namespace: go-gator
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: go-gator-fetching-job
              image: qniw984/news-fetching-job:1.1.0
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /tmp/
                  name: go-gator-pv
          restartPolicy: OnFailure
          volumes:
            - name: go-gator-pv
              persistentVolumeClaim:
                claimName: go-gator-pvc