apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    feed-group-source: "true"
  name: feed-group-source
  namespace: operator-system
data:
  sport: "washingtontimes"
  politic: "abc,bbc"
  zzaaa: "abc,washingtontimes"