apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-gator-hpa
  namespace: go-gator
spec:
  scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: go-gator
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80