apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-gator-hpa
  namespace: go-gator
spec:
  scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: go-gator
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300