apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-gator-pv
  namespace: go-gator
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/data/"
