apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-gator-service-binding
  namespace: go-gator
subjects:
  - kind: ServiceAccount
    name: go-gator-service
    apiGroup: ""
    namespace: go-gator
roleRef:
  kind: Role
  name: go-gator-service
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron-job-sa-binding
  namespace: go-gator
subjects:
  - kind: ServiceAccount
    name: cron-job-sa
    apiGroup: ""
    namespace: go-gator
roleRef:
  kind: Role
  name: cron-job-role
  apiGroup: rbac.authorization.k8s.io