apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-gator-service
  namespace: go-gator
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cron-job-role
  namespace: go-gator
