apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-gator-user-binding
  namespace: go-gator
subjects:
  - kind: ServiceAccount
    name: go-gator-user
    apiGroup: ""
    namespace: go-gator
roleRef:
  kind: Role
  name: go-gator-user
  apiGroup: rbac.authorization.k8s.io

