apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-developer-binding
  namespace: go-gator
subjects:
  - kind: ServiceAccount
    name: user-developer
    apiGroup: ""
    namespace: go-gator
roleRef:
  kind: Role
  name: user-developer
  apiGroup: rbac.authorization.k8s.io
