apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-role-binding
  namespace: go-gator
subjects:
  - kind: User
    name: user1
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user1-role