apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-gator-service
  namespace: go-gator
automountServiceAccountToken: false
secrets:
  - name: ecr-registry-helper-secrets
imagePullSecrets:
  - name: ecr-registry-helper-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-job-sa
  namespace: go-gator
automountServiceAccountToken: false