apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: go-gator-service
  namespace: go-gator
automountServiceAccountToken: false
secrets:
  - name: ecr-registry-helper-secrets
imagePullSecrets:
  - name: ecr-registry-helper-secrets
