apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-gator-service
  namespace: go-gator
automountServiceAccountToken: true
secrets:
  - name: cert-secret
    namespace: go-gator
  - name: ecr-registry-helper-secrets
    namespace: go-gator
imagePullSecrets:
  - name: ecr-registry-helper-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-job-sa
  namespace: go-gator
automountServiceAccountToken: false