apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: go-gator-vpa
  namespace: go-gator
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       go-gator
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: go-gator
      minAllowed:
        cpu: 100m
        memory: 100Mi
      maxAllowed:
        cpu: 500m
        memory: 500Mi