apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-gator-apps
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: news-aggregator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/werniq/go-gator
    path: argo-cd/apps
    targetRevision: feature/argo-cd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true