apiVersion: newsaggregator.teamdev.com/v1
kind: Source
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: source-sample
spec:
  name: bbc
  link: https://bbc.com
