on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/go-gator

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple

      - name: Log in to docker hub registry
        if: steps.rp.outputs.release_created
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata for docker push event
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Set default tag if no tags generated
        if: steps.meta.outputs.tags == ''
        run: echo "TAGS=latest" >> $GITHUB_ENV

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        if: ${{ steps.rp.outputs.release_created }}
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.rp.outputs.major }}.${{ steps.rp.outputs.minor }}.${{ steps.rp.outputs.patch }}
          labels: ${{ steps.meta.outputs.labels }}
