name: Go-Gator

on:
  [push]

jobs:
  launch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install staticcheck
        run:
          - go install honnef.co/go/tools/cmd/staticcheck@2024.1

      - name: Prepare code for launching
        run:
          go fmt ./...
          go vet ./...
          go mod tidy
          staticcheck ./...

      - name: Test application
        run:
          mkdir pkg_tests
          go test ./... -c -o ./pkg_tests
          
          ./pkg_tests/server.test
          ./pkg_tests/handlers.test
          ./pkg_tests/templates.test
          ./pkg_tests/parsers.test
          ./pkg_tests/filters.test
          ./pkg_tests/validator.test

      - name: Build docker image
        run:
          docker build -t go-gator .
