name: Go-Gator

on:
  [push]

jobs:
  launch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install go-tools using go get
        run:
          go get -u honnef.co/go/tools

      - name: Explicit installment of staticcheck
        run:
          go install honnef.co/go/tools/cmd/staticcheck@2023.1.7

      - name: Install go-task with curl
        run:
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Format code using go fmt
        run: task fmt

      - name: Check for differences after fmt
        id: check-diff
        run: |
          if ! git diff --quiet; then
            echo "::set-output name=has-diff::true"
          else
            echo "::set-output name=has-diff::false"
          fi

      - name: Check for differences after fmt
        if: steps.check-diff.outputs.has-diff
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Go fmt formatted files. Please, prepare files before pushing to the main branch. Exiting...')

      - name: Analyze code for bugs and errors
        run: task vet

      - name: Clean go.mod dependencies
        run: task clean

      - name: Run staticcheck on the project
        run: task stch

      - name: Test application
        run: task test

      - name: Build docker image
        run:
          docker build -t go-gator .